export const orderStatuses = {
  QUEUED: "Queued",
  PREPARING: "Preparing",
  READY: "Ready",
  COMPLETED: "Completed",
};

export const menuItems = [
  {
    id: "classic-english-breakfast",
    name: "Classic English Breakfast",
    category: "Breakfast",
    description: "A refined morning plate with eggs, sausage, toast, and a full breakfast finish.",
    price: 850,
    waitMinutes: 15,
    availability: "Available",
    rating: 4.8,
    tags: ["Halal", "Protein"],
    image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "pancakes-maple-syrup",
    name: "Pancakes with Maple Syrup",
    category: "Breakfast",
    description: "Fluffy stacked pancakes finished with maple syrup and a softly indulgent breakfast touch.",
    price: 650,
    waitMinutes: 12,
    availability: "Available",
    rating: 4.7,
    tags: ["Vegetarian", "Dairy"],
    image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "grilled-chicken-caesar-salad",
    name: "Grilled Chicken Caesar Salad",
    category: "Lunch",
    description: "Crisp greens, grilled chicken, and a creamy Caesar finish for a light yet satisfying lunch.",
    price: 950,
    waitMinutes: 14,
    availability: "Available",
    rating: 4.7,
    tags: ["Halal", "Protein"],
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "beef-burger-fries",
    name: "Beef Burger & Fries",
    category: "Lunch",
    description: "A juicy gourmet burger served with golden fries for a familiar crowd favorite.",
    price: 1100,
    waitMinutes: 18,
    availability: "Limited",
    rating: 4.8,
    tags: ["Halal", "Protein"],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "grilled-salmon-lemon-butter",
    name: "Grilled Salmon with Lemon Butter",
    category: "Dinner",
    description: "Perfectly grilled salmon finished with lemon butter for an elegant dinner experience.",
    price: 1650,
    waitMinutes: 22,
    availability: "Available",
    rating: 4.9,
    tags: ["Protein", "Gluten-Free"],
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "steak-garlic-mashed-potatoes",
    name: "Steak with Garlic Mashed Potatoes",
    category: "Dinner",
    description: "A premium steak plate paired with smooth garlic mashed potatoes and rich flavor.",
    price: 1700,
    waitMinutes: 24,
    availability: "Limited",
    rating: 5.0,
    tags: ["Halal", "Protein"],
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "chocolate-lava-cake",
    name: "Chocolate Lava Cake",
    category: "Desserts",
    description: "A warm chocolate-centered dessert with a luxurious, indulgent finish.",
    price: 650,
    waitMinutes: 11,
    availability: "Available",
    rating: 4.9,
    tags: ["Vegetarian", "Dairy"],
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "cheesecake-berry-sauce",
    name: "Cheesecake with Berry Sauce",
    category: "Desserts",
    description: "Smooth cheesecake topped with berry sauce for a bright and elegant dessert close.",
    price: 700,
    waitMinutes: 9,
    availability: "Limited",
    rating: 4.8,
    tags: ["Vegetarian", "Dairy"],
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "citrus-herb-chicken",
    name: "Citrus Herb Chicken",
    category: "Dinner",
    description: "Tender chicken with bright citrus, herbs, and seasonal vegetables.",
    price: 1420,
    waitMinutes: 20,
    availability: "Available",
    rating: 4.6,
    tags: ["Protein"],
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "vegetable-stir-fry",
    name: "Vegetable Stir Fry",
    category: "Lunch",
    description: "Colorful vegetables tossed with a fresh, vibrant finish for a lighter dining choice.",
    price: 800,
    waitMinutes: 13,
    availability: "Available",
    rating: 4.4,
    tags: ["Vegan", "Gluten-Free"],
    image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?auto=format&fit=crop&w=900&q=80",
  },
];
